name: Score tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: install pytest and pytest-cov
        run: pip install pytest pytest-cov flake-8
      - name: runtest to find coverage
        run: pytest --cov
